//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalASP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pedido
    {
        public int idPedido { get; set; }
        [Required(ErrorMessage = "Seleccione el estado")]
        public string Estado { get; set; }
        [Required(ErrorMessage = "Ingrese la direccion")]
        public string Direccion { get; set; }
        [Required(ErrorMessage = "Agregue productos")]
        public string Productos { get; set; }
        [Required(ErrorMessage = "Seleccione el cliente")]
        public Nullable<int> Cliente { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
    }
}
