//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalASP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Producto
    {
        public int idProducto { get; set; }
        [Required(ErrorMessage = "Ingrese la referencia")]
        public string Referencia { get; set; }
        [Required(ErrorMessage = "Ingrese el nombre")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "Ingrese el precio")]
        public Nullable<int> Precio { get; set; }
        [Required(ErrorMessage = "Seleccione el proveedor")]
        public Nullable<int> Proveedor { get; set; }
    
        public virtual Proveedor Proveedor1 { get; set; }
    }
}
