/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.util.List;
import javax.swing.JOptionPane;
import webservices.Afiliado;
import webservices.Poliza;
import webservices.Siniestro;

/**
 *
 * @author Andres
 */
public class EditarCliente extends javax.swing.JFrame {

    /**
     * Creates new form EditarCliente
     */
    public EditarCliente() {
        initComponents();
        List<Afiliado>listaAfiliado = consultaAll();
        for (Afiliado afiliado : listaAfiliado) {
            cmbCliente.addItem(afiliado.getDocumento()+" - "+afiliado.getNombre()+" "+afiliado.getApellido());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnAtras2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        cmbCliente = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtFechaNacimiento = new javax.swing.JTextField();
        txtDepartamento = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtFechaSiniestro = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cmbGenero = new javax.swing.JComboBox<>();
        cmbEstadoCivil = new javax.swing.JComboBox<>();
        cmbTipoPoliza = new javax.swing.JComboBox<>();
        cmbValorPoliza = new javax.swing.JComboBox<>();
        cmbTipoSiniestro = new javax.swing.JComboBox<>();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Editar Cliente");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        btnAtras2.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andres\\Documents\\NetBeansProjects\\SegurosClient\\src\\Recursos\\Circled Left 2_35px.png")); // NOI18N
        btnAtras2.setText("Atras");
        btnAtras2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtras2MouseClicked(evt);
            }
        });
        jPanel3.add(btnAtras2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andres\\Documents\\NetBeansProjects\\SegurosClient\\src\\Recursos\\Shutdown_15px.png")); // NOI18N
        jLabel21.setText("Cerrar Sesión");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 90));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 60, 642, 10));

        jLabel4.setText("Cliente");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        cmbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un cliente" }));
        cmbCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbClienteItemStateChanged(evt);
            }
        });
        cmbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClienteActionPerformed(evt);
            }
        });
        jPanel4.add(cmbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 165, 32));

        jLabel5.setText("Informacion Personal");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 43, -1, -1));

        jLabel6.setText("Nombre");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));
        jPanel4.add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, 30));
        jPanel4.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 150, 30));
        jPanel4.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 150, 30));
        jPanel4.add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 150, 30));
        jPanel4.add(txtDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 150, 30));
        jPanel4.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 150, 30));
        jPanel4.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 150, 30));

        jLabel7.setText("Apellido");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        jLabel8.setText("Fecha de nacimiento (aaaa-mm-dd)");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel9.setText("Genero");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        jLabel10.setText("Departamento");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        jLabel11.setText("Ciudad");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel12.setText("Direccion");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        jLabel13.setText("Estado civil");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, -1));

        jLabel14.setText("Documento");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 280, 10));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 280, 10));

        jLabel15.setText("Informacion de la poliza adquirida");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel16.setText("Informacion de siniestros");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));
        jPanel4.add(txtFechaSiniestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 200, 30));

        jLabel17.setText("Tipo de poliza");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel18.setText("Valor de la poliza");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel19.setText("Fecha del siniestro");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        jLabel20.setText("Tipo de siniestro");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        cmbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Masculino", "Femenino", "Otro" }));
        jPanel4.add(cmbGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 150, 30));

        cmbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Soltero", "Casado", "Divorciado", "Viudo" }));
        jPanel4.add(cmbEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 150, 30));

        cmbTipoPoliza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "SOAT", "Voluntaria del hogar" }));
        jPanel4.add(cmbTipoPoliza, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 200, 30));

        cmbValorPoliza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "68000", "130000" }));
        jPanel4.add(cmbValorPoliza, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 200, 30));

        cmbTipoSiniestro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Natural", "Suicidio", "Asesinato" }));
        jPanel4.add(cmbTipoSiniestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 200, 30));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel4.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 110, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 690, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtras2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtras2MouseClicked
        // TODO add your handling code here:
        new IndexAdministrador().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAtras2MouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        
        String documentoAfiliado[] = String.valueOf(cmbCliente.getSelectedItem()).split("-");
        int idAfiliado = clienteBuscar(documentoAfiliado[0]);
        int resultAfiliado = cliente("Editar/"+documentoAfiliado[0]+"", txtDocumento.getText(), txtNombre.getText(), txtApellido.getText(), txtFechaNacimiento.getText(), String.valueOf(cmbGenero.getSelectedItem()), txtDepartamento.getText(), txtCiudad.getText(), txtDireccion.getText(), String.valueOf(cmbEstadoCivil.getSelectedItem()), "Activo");
        if (resultAfiliado == 200) {
            
            
            int resultEditarPoliza = editarPoliza(String.valueOf(cmbTipoPoliza.getSelectedItem()), Double.parseDouble(String.valueOf(cmbValorPoliza.getSelectedItem())), idAfiliado);
            if (resultEditarPoliza == 200) {
               
                if (txtFechaSiniestro.getText() != "") {
                    
                    Afiliado objAfiliado = new Afiliado();
                    objAfiliado.setIdAfiliado(idAfiliado);
                    Siniestro objSiniestro = new Siniestro();
                    objSiniestro.setAfiliado(objAfiliado);
                    objSiniestro.setTipo(String.valueOf(cmbTipoSiniestro.getSelectedItem()));
                    int resultadoEditarSiniestro = editarSiniestro(objSiniestro);
                    if (resultadoEditarSiniestro == 200) {
                        JOptionPane.showMessageDialog(this, "Datos editados exitosamente.");
                        new ClientesRegistrados().setVisible(true);
                        this.setVisible(false);
                        
                    }else{
                        JOptionPane.showMessageDialog(this, "Error el editar los datos del Cliente, por favor verifique sus datos e intentelo de nuevo");
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Datos editados exitosamente.");
                }
            }
            
        }else{
            
            JOptionPane.showMessageDialog(this, "Error el editar los datos del Cliente, por favor verifique sus datos e intentelo de nuevo");
        }
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void cmbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbClienteActionPerformed

    private void cmbClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbClienteItemStateChanged
        // TODO add your handling code here:
        List<Afiliado>listafiliado = buscarDatosCliente(cmbCliente.getSelectedIndex());
        for (Afiliado afiliado : listafiliado) {
            String fecha[] = String.valueOf(afiliado.getFechaNacimiento()).split("T");
            txtDocumento.setText(afiliado.getDocumento());
            txtNombre.setText(afiliado.getNombre());
            txtApellido.setText(afiliado.getApellido());
            txtFechaNacimiento.setText(fecha[0]);
            txtDepartamento.setText(afiliado.getDepartamento());
            txtCiudad.setText(afiliado.getCiudad());
            txtDireccion.setText(afiliado.getDireccion());
            if (afiliado.getGenero().equals("Masculino")) {
                cmbGenero.setSelectedIndex(1);
            }else if (afiliado.getGenero().equals("Femenino")) {
                cmbGenero.setSelectedIndex(2);
            }else{
                cmbGenero.setSelectedIndex(3);
            }
            
            if (afiliado.getEstadoCivil().equals("Soltero")) {
                cmbEstadoCivil.setSelectedIndex(1);
            }else if (afiliado.getEstadoCivil().equals("Casado")) {
                cmbEstadoCivil.setSelectedIndex(2);
            }else if (afiliado.getEstadoCivil().equals("Divorciado")) {
                cmbEstadoCivil.setSelectedIndex(3);
            }else{
                cmbEstadoCivil.setSelectedIndex(4);
            }
            
            List<Poliza>listaPoliza = polizaBuscar(afiliado.getIdAfiliado());
            for (Poliza poliza : listaPoliza) {
                if (poliza.getTipo().equals("SOAT")) {
                    cmbTipoPoliza.setSelectedIndex(1);
                }else{
                    cmbTipoPoliza.setSelectedIndex(2);
                }
                if (poliza.getValor() == 68000) {
                    cmbValorPoliza.setSelectedIndex(1);
                }else{
                    cmbValorPoliza.setSelectedIndex(2);
                }
            }
            
            List<Siniestro>listasiniestro = siniestroBuscar(afiliado.getIdAfiliado());
            if (listasiniestro.size() > 0) {
                txtFechaSiniestro.setEnabled(true);
                cmbTipoSiniestro.setEnabled(true);
                for (Siniestro siniestro : listasiniestro) {
                    String fechaSiniestro[] = String.valueOf(siniestro.getFecha()).split("T");
                    txtFechaSiniestro.setText(fechaSiniestro[0]);
                    if (siniestro.getTipo().equals("Natural")) {
                        cmbTipoSiniestro.setSelectedIndex(1);
                    }else if (siniestro.getTipo().equals("Suicidio")) {
                        cmbTipoSiniestro.setSelectedIndex(2);
                    }else{
                        cmbTipoSiniestro.setSelectedIndex(3);
                    }
                }
            }else{
                txtFechaSiniestro.setEnabled(false);
                cmbTipoSiniestro.setEnabled(false);
                txtFechaSiniestro.setText("");
                cmbTipoSiniestro.setSelectedIndex(0);
            }
            
        }
    }//GEN-LAST:event_cmbClienteItemStateChanged

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel21MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAtras2;
    private javax.swing.JButton btnEditar;
    private javax.swing.JComboBox<String> cmbCliente;
    private javax.swing.JComboBox<String> cmbEstadoCivil;
    private javax.swing.JComboBox<String> cmbGenero;
    private javax.swing.JComboBox<String> cmbTipoPoliza;
    private javax.swing.JComboBox<String> cmbTipoSiniestro;
    private javax.swing.JComboBox<String> cmbValorPoliza;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtDepartamento;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtFechaSiniestro;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private static java.util.List<webservices.Afiliado> consultaAll() {
        webservices.WSSeguros_Service service = new webservices.WSSeguros_Service();
        webservices.WSSeguros port = service.getWSSegurosPort();
        return port.consultaAll();
    }

    private static int clienteBuscar(java.lang.String documento) {
        webservices.WSSeguros_Service service = new webservices.WSSeguros_Service();
        webservices.WSSeguros port = service.getWSSegurosPort();
        return port.clienteBuscar(documento);
    }

    private static java.util.List<webservices.Afiliado> buscarDatosCliente(int idAfiliado) {
        webservices.WSSeguros_Service service = new webservices.WSSeguros_Service();
        webservices.WSSeguros port = service.getWSSegurosPort();
        return port.buscarDatosCliente(idAfiliado);
    }

    private static java.util.List<webservices.Siniestro> siniestroBuscar(int idAfiliado) {
        webservices.WSSeguros_Service service = new webservices.WSSeguros_Service();
        webservices.WSSeguros port = service.getWSSegurosPort();
        return port.siniestroBuscar(idAfiliado);
    }

    private static java.util.List<webservices.Poliza> polizaBuscar(int idAfiliado) {
        webservices.WSSeguros_Service service = new webservices.WSSeguros_Service();
        webservices.WSSeguros port = service.getWSSegurosPort();
        return port.polizaBuscar(idAfiliado);
    }

    private static int cliente(java.lang.String accion, java.lang.String documento, java.lang.String nombre, java.lang.String apellido, java.lang.String fechaNacimiento, java.lang.String genero, java.lang.String departamento, java.lang.String ciudad, java.lang.String direccion, java.lang.String estadoCivil, java.lang.String estado) {
        webservices.WSSeguros_Service service = new webservices.WSSeguros_Service();
        webservices.WSSeguros port = service.getWSSegurosPort();
        return port.cliente(accion, documento, nombre, apellido, fechaNacimiento, genero, departamento, ciudad, direccion, estadoCivil, estado);
    }

    private static int editarSiniestro(webservices.Siniestro arg0) {
        webservices.WSSeguros_Service service = new webservices.WSSeguros_Service();
        webservices.WSSeguros port = service.getWSSegurosPort();
        return port.editarSiniestro(arg0);
    }

    private static int editarPoliza(java.lang.String tipo, double valor, int afiliado) {
        webservices.WSSeguros_Service service = new webservices.WSSeguros_Service();
        webservices.WSSeguros port = service.getWSSegurosPort();
        return port.editarPoliza(tipo, valor, afiliado);
    }

}
