/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.util.List;
import javax.swing.JOptionPane;
import webservices.Afiliado;
import webservices.Siniestro;

/**
 *
 * @author Andres
 */
public class RegistroSiniestro extends javax.swing.JFrame {

    /**
     * Creates new form RegistroSiniestro
     */
    public RegistroSiniestro() {
        initComponents();
        List<Afiliado>listaAfiliados = consultaAll();
        for (Afiliado afiliado : listaAfiliados) {
            List<Siniestro>listaSiniestro = siniestroBuscar(afiliado.getIdAfiliado());
            if (listaSiniestro.size() == 0) {
                cmbCliente.addItem(afiliado.getDocumento()+" - "+afiliado.getNombre()+" "+afiliado.getApellido());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnAtras7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        cmbCliente = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnRegistrarSiniestro = new javax.swing.JButton();
        cmbTipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Registrar Siniestro");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        btnAtras7.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andres\\Documents\\NetBeansProjects\\SegurosClient\\src\\Recursos\\Circled Left 2_35px.png")); // NOI18N
        btnAtras7.setText("Atras");
        btnAtras7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtras7MouseClicked(evt);
            }
        });
        jPanel8.add(btnAtras7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andres\\Documents\\NetBeansProjects\\SegurosClient\\src\\Recursos\\Shutdown_15px.png")); // NOI18N
        jLabel5.setText("Cerrar Sesión");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, -1, -1));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 90));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Cliente" }));
        jPanel9.add(cmbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 291, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Cliente");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));
        jPanel9.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 290, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Fecha (aaaa-mm-dd)");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Tipo");
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        btnRegistrarSiniestro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegistrarSiniestro.setText("Registrar");
        btnRegistrarSiniestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarSiniestroActionPerformed(evt);
            }
        });
        jPanel9.add(btnRegistrarSiniestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 190, 50));

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Natural", "Suicidio", "Asesinato" }));
        jPanel9.add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 290, 40));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 690, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtras7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtras7MouseClicked
        // TODO add your handling code here:
        new IndexAdministrador().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAtras7MouseClicked

    private void btnRegistrarSiniestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarSiniestroActionPerformed
        // TODO add your handling code here:
        String Afiliado = String.valueOf(cmbCliente.getSelectedItem());
        String documentoAfiliado[] = Afiliado.split("-");
        int idAfiliado = clienteBuscar(documentoAfiliado[0]);
        int result = siniestroCreate(txtFecha.getText(), String.valueOf(cmbTipo.getSelectedItem()), idAfiliado);
        if (result == 201) {
            JOptionPane.showMessageDialog(this, "Siniestro registrado exitosamente.");
            new SiniestrosRegistrados().setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(this, "Error al crear el registro, por favor intentalo mas tarde.");
        }
    }//GEN-LAST:event_btnRegistrarSiniestroActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroSiniestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroSiniestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroSiniestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroSiniestro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroSiniestro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAtras7;
    private javax.swing.JButton btnRegistrarSiniestro;
    private javax.swing.JComboBox<String> cmbCliente;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField txtFecha;
    // End of variables declaration//GEN-END:variables

    private static java.util.List<webservices.Afiliado> consultaAll() {
        webservices.WSSeguros_Service service = new webservices.WSSeguros_Service();
        webservices.WSSeguros port = service.getWSSegurosPort();
        return port.consultaAll();
    }

    private static java.util.List<webservices.Siniestro> siniestroBuscar(int idAfiliado) {
        webservices.WSSeguros_Service service = new webservices.WSSeguros_Service();
        webservices.WSSeguros port = service.getWSSegurosPort();
        return port.siniestroBuscar(idAfiliado);
    }

    private static int siniestroCreate(java.lang.String fecha, java.lang.String tipo, int afiliado) {
        webservices.WSSeguros_Service service = new webservices.WSSeguros_Service();
        webservices.WSSeguros port = service.getWSSegurosPort();
        return port.siniestroCreate(fecha, tipo, afiliado);
    }

    private static int clienteBuscar(java.lang.String documento) {
        webservices.WSSeguros_Service service = new webservices.WSSeguros_Service();
        webservices.WSSeguros port = service.getWSSegurosPort();
        return port.clienteBuscar(documento);
    }
}
